### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ThePlenkov** [ZJONSSON/node-unzipper#101]
Hi,

when I'm trying to uzip the following file: https://tools.hana.ondemand.com/additional/sapui5-rt-1.44.42.zip

I have some console message:
```
(node:13812) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```

I'm just using pipe(unzipper.Extract({ path }));

Do you have any recommendations to limit memory usage during the extraction?

Thank you!

**Comment by ZJONSSON** [comment]
`unzipper` is designed to be extremely memory efficient (as it is entirely stream based with backpressure support).   Please check memory usage to see if there are any issues?

MaxListenerWarning is just a warning indicating a "possible" memory leak due to multiple event listeners.     See more in the [node documentation](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n).  You can turn of this warning by including `emitter.setMaxListeners(0)`

If is possible that there are some listeners that aren't removed, if you find any please do a PR.  In any case their effect on memory should be very small.
