### ISSUE TITLE
How to count files inside large zip in AWS S3 without downloading it?

### ISSUE THREAD

**Issue by Badamgarav** [ZJONSSON/node-unzipper#110]
My zip file's size 4.98GB, and 10000 images inside a zip.  The zip file has been uploaded to S3.
My code is: 

    async function getNumber() {
        try {
           const directory = await unzipper.Open.s3(s3, {Bucket: 'bucket', Key: 'key'}).catch(error => {
               console.error('catching:: ', error);
               throw error
           });
           console.log('counter::', directory.files.length);  //or directory.numberOfRecords
       } catch (error) {
           console.log()
       }
     } 

I am getting this error: 

    throw er; // Unhandled 'error' event
      ^
    Error: FILE_ENDED
       at PullStream.pull 
     (D:\tutorial_projects\testlambda\node_modules\unzipper\lib\PullStream.js:76:28)
       at emitOne (events.js:116:13)
       at PullStream.emit (events.js:211:7)
       at PullStream.<anonymous> 
    (D:\tutorial_projects\testlambda\node_modules\unzipper\lib\PullStream.js:20:10)
       at emitNone (events.js:111:20)
       at PullStream.emit (events.js:208:7)
       at finishMaybe (_stream_writable.js:614:14)
       at endWritable (_stream_writable.js:622:3)
       at PullStream.Writable.end (_stream_writable.js:573:5)
       at PassThrough.onend (_stream_readable.js:595:10)
       at Object.onceWrapper (events.js:313:30)
       at emitNone (events.js:111:20)
       at PassThrough.emit (events.js:208:7)
       at endReadableNT (_stream_readable.js:1064:12)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
       at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by ZJONSSON** [comment]
Since this is happening at `Open` the unzipper is not seeing the end of central directory signature (`0x06054b50`) before the file ends.  There are two potential reasons for that:
* The file you are getting from s3 is not the zipfile, but rather an access denied response
* The size  of the end-of-central-directory is larger than the 40 bytes assumed by unzipper

Can you first inspect that  `s3.getObject` (using the same `s3` variable as you pass to unzipper) actually returns the zip file, not an error message?  

Can you try locally to modify the value `40` to something bigger in [this line](https://github.com/ZJONSSON/node-unzipper/blob/master/lib/Open/directory.js#L20) and try again

**Comment by ZJONSSON** [comment]
You can also try [this branch](https://github.com/ZJONSSON/node-unzipper/commit/289fdcd8dade352fed2e4f10be0704679f333669) where you can specify tailSize (number of bytes) as an option.  You can check out the branch by `npm install zjonsson/node-unzipper#tailsize`

**Comment by ZJONSSON** [comment]
I increased default tailSize  to 80 bytes, but you can also supply custom `tailSize` in a new options object (additional argument to the `Open` methods).  See readme.

published as `+ unzipper@0.10.0`.  Please reopen if issue is not resolved
