### ISSUE TITLE
Unzipper changes my folder's permissions to write only

### ISSUE THREAD

**Issue by mateoc10** [ZJONSSON/node-unzipper#131]
I am having a problem that after unzipping, the extracted folder changes its permissions to write only, so I can not read it.
I'm doing this:
```
return new Promise<boolean>((resolve, reject) => {
        fse.createReadStream(zipLocation)
            .pipe(unzipper.Extract({ path: __dirname }))
            .on('finish', () => {
                resolve(folderExists())
                }
            })
    });
```

Am I doing something wrong?
I zipped the folder on a Mac right clicking and selecting compress. I also tried with a program named Keka and the same happened

**Comment by ZJONSSON** [comment]
> I zipped the folder on a Mac right clicking and selecting compress. I also tried with a program named Keka and the same happened

If the same thing happened with Keka and unzipper I'm guessing this problem is not attributable to unzipper.    

The `extract` function is powered by `fstream.Writer` (see [fstream](https://www.npmjs.com/package/fstream)) - if the issue you are experiencing is due to `fstream` please raise an issue or submit a PR [here](https://github.com/npm/fstream/issues)

You can also provide your own `writer` in the [options to extract](https://github.com/ZJONSSON/node-unzipper/blob/master/lib/extract.js#L29).  The `writer` needs to be a function (receiving destination `path` as a variable to the provided options) that returns a writable stream that consumes the file.

If you pinpoint a specific issue that is directly related to `unzipper` directly, please reopen or submit a more detailed description.
