### ISSUE TITLE
Is it possible to await entry.pipe?

### ISSUE THREAD

**Issue by owenniblock** [ZJONSSON/node-unzipper#138]
We have the following code:

```
  public getMergeXmlResultsPromise(pathToArchive: string, tempPath: string, processXml: Function, resolvePromise: Function): Promise<Document> {
    return new Promise<Document>((resolve, reject) => {
      fs.createReadStream(pathToArchive)
        .pipe(unzipper.Parse())
        .on("entry", async function (entry: unzipper.Entry) {
          // Skip directories and hidden system files
          if (entry.type === "Directory" || path.basename(entry.path).substring(0, 1) === ".") {
            entry.autodrain();
            return;
          }
          const fullPath: string = path.join(tempPath, entry.path);
          console.log(fullPath);
          entry.pipe(fs.createWriteStream(fullPath)).on("finish", () => {
            try {
              console.log(fullPath);
              processXml(fullPath, entry.path);
            } catch (e) {
              console.log(fullPath + ": " + e);
              reject(e);
            }
          });
        })
        .promise()
        .then(
          () => resolvePromise(resolve),
          (e) => console.log("error", e)
        );
    });
  }
```

Which works for small files but when the files get large it looks like it's resolving the promise before it gets to the `.on("finish"..)`

I tried tinkering with various async / awaits but haven't managed to get it to do what I want.

Is this possible? Or should I just completely unzip the directory and then do it with less piping?

**Comment by ZJONSSON** [comment]
Yeah absolutely.  The problem is that the `pipe` chain finishes when the zip file has been read, not when the output files have been written.   For small files this is roughly the same thing, but for large files there can be a some lag.

If you are using `unzipper.Parse()` one way to tackle this is to use `.pipe` into a `transform` stream that only performs callback when each file has been written.   You can see some examples in the readme here: https://www.npmjs.com/package/unzipper#parse-zip-by-piping-entries-downstream

If you wanted to ensure you also do the `processXml` before finally resolving, you would simply need to  place it before `cb` i.e. for first example:

```js
   if (fileName === "this IS the file I'm looking for") {
        entry.pipe(fs.createWriteStream('output/path'))
          .on('finish',() => {
            try {
              processXml(fullPath, entry.path);
              cb();
            } catch(err) {
              cb(err);
            }
         })
```

or in the second example:
```js
  .pipe(etl.map(async entry => {
    if (entry.path == "this IS the file I'm looking for") {
      await entry
        .pipe(etl.toFile('output/path'))
        .promise();
      try {.....}
    } else {
      entry.autodrain();
   }
  }))
```

Few comments on the pattern here.   
* If `processXml` is an async function, we can not guarantee it has finished when the top level promise here is resolved.  So you would want to await on it as well. 
* If it's a synchronous function, it might be using `readFileSync` which is usually a bad function since it blocks the event loop while reading the file.
* Usually there should be no need to write to a temporary file and then parse xml from a temporary file.  You should be able to parse the xml directly from the entry stream.    An example of a streaming xmler parser is [xmler](https://www.npmjs.com/package/xmler) which uses [node-expat](https://www.npmjs.com/package/node-expat) under the coves.

Here is an example of a streaming XML parse from a zip file (in this case an xlsx file which is a zip):

```js
const unzipper = require('unzipper');
const etl = require('etl');
const request = require('request');
const xmler = require('xmler');

async function main() {
  return request('https://www.hud.gov/sites/documents/RM-A_07-31-2014.xlsx')
    .pipe(unzipper.ParseOne('xl/worksheets/sheet1.xml'))
    .pipe(xmler('row'))
    .pipe(etl.map(row => console.log(JSON.stringify(row))))
    .promise();
}

main()
  .then(() => console.log('done'), e => console.log('error',e));
```

**Comment by owenniblock** [comment]
I can't work out how you're using `stream.Transform`

I can import from `stream` - but then I have to use `new stream.Transform` and the line `transform: function(entry,e,cb) {` has the wrong type for `entry`.

I guess I'm just misunderstanding where `stream.Transform` should be coming from?

**Comment by owenniblock** [comment]
P.S. We're writing out and parsing because we've had trouble with files not merging correctly and it's harder to track if we've for streams flying around everywhere :) and also because we were using `unzip` until recently and it had a load of bugs 😆

**Comment by owenniblock** [comment]
We. solved this by simplifying the workflow, writing out to a temp directory and then processing it from there. It turned out that some of the XML. files were massive and part of the problem was a memory issue with the XML library we were using.

Streaming is neat - but I think we'll leave it as it is for now :)

Thanks for your help!
