### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by straussCS** [ZJONSSON/node-unzipper#141]
In Electron 5.0.7 / node 10.16.0 i am getting the following warning:

```
internal/process/warning.js:23 (node:11744) [DEP0005] 
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
writeOut @ internal/process/warning.js:23
onWarning @ internal/process/warning.js:76
emit @ events.js:194
(anonymous) @ internal/process/warning.js:49
processTicksAndRejections @ internal/process/task_queues.js:79
```

**Comment by ZJONSSON** [comment]
Are you sure this is coming from `unzipper`?  If so can you try to figure out where from?
To my understanding this error comes from using `new Buffer()` instead of `Buffer.from()` or `Buffer.alloc()` (see [here](https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/))

`new Buffer()` is used in one place, a polyfill for node versions < 8 which are missing `Buffer.from`, but that code should not execute on any newer versions of node.

I have kept the legacy compatibility to ensure that `unzipper` remains a drop-in replacement for `unzip`

**Comment by straussCS** [comment]
The Warning is gone once I remove
`this.unzipper = require("unzipper");`
This was what led me here.
I am also suspecting the code you mentioned, but it doesn't seem to be executed when checking with a debugger.

**Comment by ZJONSSON** [comment]
Interesting - I thought we did not have any links to the deprecated `new Buffer` as I see no warning when I run the tests.   It is possible this is coming from some of the dependencies.    Please let me know if you find out more, I will do some digging as well.

**Comment by ZJONSSON** [comment]
@straussCS can you recreate this with a very simple example?   I've been unable to see this warning locally.

**Comment by straussCS** [comment]
@ZJONSSON I could not reproduce the issue with a minimal electron setup. The warning might be caused by something in my projects' build process (I am using https://github.com/maximegris/angular-electron). 

I will investigate further, please close this issue as you see fit. There is probably no direct connection to this package.

**Comment by ZJONSSON** [comment]
Thanks @straussCS - please reopen if you find out any direct linkage

**Comment by swapzone** [comment]
@ZJONSSON the problem lies with the `buffer-indexof-polyfill` modules that you are referencing in your package.json. It does the following check `if (new Buffer ("ABC").lastIndexOf ("ABC") === -1) {` in case `Buffer.prototype.lastIndexOf` is defined (which should be the case for all recent Node.js versions).

This causes the issue for me mentioned in this ticket.
