### ISSUE TITLE
Some zip files never resolve buffer()

### ISSUE THREAD

**Issue by msamblanet** [ZJONSSON/node-unzipper#181]
I am trying to use the Open methods to read a single file into a buffer.  However, my code seems to only work with some ZIPs and not others.  The sample below shows the logic working with compressed-directory-entry/archive.zip but not with big.zip (both from the testData folder).

When I run this code, I get to "D2" being logged, but "E2" never is logged and the promise is neither resolved or rejected...

```
async function bufferTest() {
    src = "testData/compressed-directory-entry/archive.zip";
    innerFile = "index.html";

    console.log("A");
    directory = await unzipper.Open.file(src);
    console.log("B");
    file = directory.files.find(d => d.path === innerFile);
    console.log("C");
    if (!file) throw new Error(`Unable to locate ${innerFile} in ${src}`);
    console.log("D");
    buffer = await file.buffer();
    console.log("E");


    src = "./testData/big.zip";
    innerFile = "big.dat";

    console.log("A2");
    directory = await unzipper.Open.file(src);
    console.log("B2");
    file = directory.files.find(d => d.path === innerFile);
    console.log("C2");
    if (!file) throw new Error(`Unable to locate ${innerFile} in ${src}`);
    console.log("D2");
    buffer = await file.buffer();
    console.log("E2");
}
bufferTest()
.then(() => console.log("Done"))
.catch((err) => console.log(err));
```

**Comment by ZJONSSON** [comment]
Thanks for the report @msamblanet - I can only help you debug this if you share a file that doesn't work.   You can email me at: ziggy.jonsson.nyc@gmail.com

**Comment by msamblanet** [comment]
The sample above uses zips out of the GIT repo - the failure is with big.zip in the test data folder.  I ran the above code by cloning the repo, npm install'ing, and pasting the code into an interactive Node console.

**Comment by ZJONSSON** [comment]
Got it - please make sure you are using the latest version of `unzipper` ( 0.10.10)

When I run this script the last file takes a few seconds and then throws the following error: 

```
uffer.js:324
    throw new ERR_INVALID_OPT_VALUE.RangeError('size', size);
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "5368709120" is invalid for option "size"
```

The problem here is that the entire buffer that needs to be generated is over 5gb in size.  There is an upper limit to the Buffer size in node defined in v8.  You can check locally by spinning up a node terminal and the following should error as well:

```
Buffer.alloc(5368709120)
```

The `.buffer` method is a convenience method to collect all the streaming data into a buffer, obviously this method is not ideal when the output is in the gigabytes.   I would recommend using the streaming methods.   For example:


Stream into a transform:

```js
    let i = 0;
    await new Promise( (resolve, reject) => file.stream()
      .pipe(require('stream').Transform({
        transform: (d, e, cb) => {
          console.log('data',i++,d);
          cb();
        }
      }))
      .on('error',reject)
      .on('finish',resolve)
    );
    console.log("E2");
```

Stream into a file:

```js
   await new Promise( (resolve, reject) => file.stream()
      .pipe(require('fs').createWriteStream('./outfile'))
      .on('error',reject)
      .on('finish',resolve)
    );
    console.log("E2");
```

**Comment by ZJONSSON** [comment]
Closing - @msamblanet please reopen if there are further issues
