### ISSUE TITLE
Not picking up last entry

### ISSUE THREAD

**Issue by edcourtney74** [ZJONSSON/node-unzipper#190]
I've been using unzipper to download zip files from s3, but a few times I've had the last entry of the zip not get picked up. This seems to happen if the file is smaller (less than 1KB).  Any ideas? The package works great, just now and then misses the last file.

```
const zip = s3.getObject({ Bucket, Key })
  .createReadStream()
  .pipe(unzipper.Parse({ forceStream: true }));

for await (const entry of zip) {
  if (entry.type === 'File' || entry.type === 'Directory') {
    doSomething;
  } else {
    entry.autodrain();
  }
}
```

**Comment by ZJONSSON** [comment]
Here is what I am guessing:   In your example, the `await` in the async iterator waits for the "start" of each file (i.e. the entry event).  Since the zip file is being read sequentially, it so happens that an entry event is only fired after the previous entry was fully consumed.   There are however no further entries after the last file and therefore execution will move out of the await state, even if the last file hasn't been fully consumed.  

So for example, this would fail on the last file:

```js
for await const entry of zip) {
  if (entry.type === 'File') {
    entry.pipe(fs.createWriteStream(entry.path))
  } else {
    entry.autodrain();
}

process.exit();
```

it would fail because the pipe to file just started and we are not waiting for it to finish before exiting.

This should work:

```js
for await const entry of zip) {
  if (entry.type === 'File') {
    await new Promise( (resolve, reject) => {
      entry.pipe(fs.createWriteStream(entry.path))
         .on('error',reject)
         .on('finish',resolve)
    });
  } else {
    entry.autodrain();
}

process.exit();
```

If you are not able to resolve this, you can always send me a (non-sensitize) zip file either here or to my email (ziggy.jonsson.nyc@gmail.com) and I can help you debug?

**Comment by edcourtney74** [comment]
I was still having some trouble using it with s3.upload, but I switched to the Open.s3 and putObject, and it's working great. Thanks for all your help.
