### ISSUE TITLE
Issue with Incorrect Character Display in `fileName`

### ISSUE THREAD

**Issue by mathmartins-sb** [ZJONSSON/node-unzipper#290]
## Issue with Incorrect Character Display in `fileName`

**Problem Description:**

When using the `unzipper` library to extract files from a ZIP archive, the `fileName` variable is displaying incorrect characters for accented characters such as á, ç, ã, etc. Someone knows how to solve?

**Example Code:**

```javascript
import unzipper from 'unzipper';
import fs from 'fs';

fs.createReadStream('./teste.zip')
  .pipe(unzipper.Parse())
  .on('entry', function (entry) {
    const fileName = entry.path;
    const type = entry.type; // 'Directory' or 'File'
    const size = entry.vars.uncompressedSize; // There is also compressedSize;
    console.log('using unzipper');
    console.log(fileName);
  });

**Comment by ZJONSSON** [comment]
[test.zip](https://github.com/ZJONSSON/node-unzipper/files/15053361/test.zip)
@mathmartins-sb  I just created a test zip file with accented characters (attached) and I did get back the accented characters both with the `.pipe(unzipper.Parse())` as well as the `.Open` methods.    Are you sure the problem is not with the process that wrote this zip files originally?   If not can you please reopen and share a sample zip file that is problematic for you

**Comment by ZJONSSON** [comment]
![image](https://github.com/ZJONSSON/node-unzipper/assets/1082488/db8f3030-d0e3-4224-8e20-410422fcb9ec)
