### ISSUE TITLE
uncompressedSize always return 0 if zip file is download from google drive

### ISSUE THREAD

**Issue by natuan62** [ZJONSSON/node-unzipper#295]
[test-unzipper-20240227T025830Z-001.zip](https://github.com/ZJONSSON/node-unzipper/files/14413747/test-unzipper-20240227T025830Z-001.zip)

![image](https://github.com/ZJONSSON/node-unzipper/assets/10808157/9c335d22-0438-45e8-89f6-bd61b9d49f73)

```js

const unzipper = require('unzipper');
const fs = require('fs');

const main = async () => {
  const zip = fs.createReadStream('./test-unzipper-20240227T025830Z-001.zip').pipe(unzipper.Parse({ forceStream: true }));
  for await (const entry of zip) {
    console.log('entry', entry);
  }
};

main();

// console.log
vars: {
    ...
    compressedSize: 0,
    uncompressedSize: 0,
      },
```

**Comment by ZJONSSON** [comment]
There are two different methods to use unzipper.  The first method is to pipe the entire zip file into an unzipper, which will read sequentially from the zip file, relying on local file headers.   The second method uses the `.Open` method, where the zip file will be read with random access based on the official information in the Central Directory.

The Central Directory is the official source of truth, and local headers can't be 100% trusted.   It seems that google is doing streaming writes and doesn't know how big each file is when writing the local file headers (because they appear above the inner file).

If you switch to the Open methods, you should see both compressedSize and uncompressedSize.

The first method of piping the entire file was inherited from the previous library called `unzip`.   I'm contemplating switching the readme around and starting with the `Open` methods and then including the stream method below as legacy.
